# Generated by Django 6.0.5 on 2026-05-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export'), ('utility', 'Utility Electricity Data'), ('travel', 'Corporate Travel Data')], max_length=50)),
                ('original_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('normalized', 'Normalized'), ('failed', 'Failed'), ('review', 'Needs Review'), ('approved', 'Approved'), ('locked', 'Audit Locked')], default='uploaded', max_length=50)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant')),
            ],
        ),
    ]
