# Generated by Django 6.0.5 on 2026-05-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_rawrecord'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=50)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('calculated_emissions', models.FloatField(help_text='Metric tons CO2 equivalent')),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('analyst_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending_review', max_length=50)),
                ('source_reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
        ),
    ]
